permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:

name: check
jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
      - name: cargo fmt --check --all
        run: cargo fmt --check --all
